version: '3'

services:

  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./frontend/dist:/opt/isucon/public
    ports:
      - "8080:80"
      - "5000:5000"
    links:
      - "webapp"
      - "payment"

  payment:
    image: golang:1.12
    volumes:
      - ../blackbox/payment:/go/src/payment
    environment:
      - "GO111MODULE=on"
    command:
      - go
      - run
      - main.go
    working_dir: /go/src/payment
    env_file:
      - ".env"

volumes:
  mysql:
